bind \cl 'forward-char'
bind \ck 'history-search-backward'
bind \cj 'history-search-forward'

alias s='svn'
alias g='gvim'
alias m='make'
alias mc='make clean'
alias mcm='make clean; make'
alias x='exit'
alias r='reset'
alias f='fg'
alias l='ls'
alias ll='ls -aFlhs'
alias lll='ls -aFlhs | less'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias sagi='sudo aptitude install'
alias sagr='sudo aptitude remove'
alias vl='vim -n -u /usr/share/vim/vim72/macros/less.vim "+set background=dark"'
alias dum='du -h --max-depth=1'
alias soc='ssh -Y soc'
alias pd='pushd -n'
alias bd='popd'
alias t='tmux'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tl='tmux ls'

alias gs='git status'
alias gb='git branch'
alias gci='git commit'
alias gp='git push'
alias gl='git pull'

. ~/.config/fish/set_paths
