bind \cl 'forward-char'
bind \ck 'history-search-backward'
bind \cj 'history-search-forward'

set -x EDITOR vim

alias vimdiff='vim -d'
alias m='make'
alias mc='make clean'
alias mcm='make clean; make'
alias x='exit'
alias r='reset'
alias f='fg'
alias l='ls'
alias ll='ls -aFlhs'
alias lll='ls -aFlhs | less'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias sagi='sudo apt install'
alias sagu='sudo apt update'
alias sagr='sudo apt upgrade'
alias sagx='sudo apt remove'
alias dum='du -h --max-depth=1'
alias pd='pushd -n'
alias bd='popd'
alias t='tmux'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tl='tmux ls'

alias gs='git status'
alias gb='git branch'
alias gci='git commit'
alias gp='git push'
alias gl='git pull'

. ~/.config/fish/fishenv
